from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName(_fromUtf8("mainWindow"))
        mainWindow.resize(862, 772)
        self.centralwidget = QtGui.QWidget(mainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout_10 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.verticalLayout_9 = QtGui.QVBoxLayout()
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.jobInfosGroupBox = QtGui.QGroupBox(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MS Shell Dlg 2"))
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.jobInfosGroupBox.setFont(font)
        self.jobInfosGroupBox.setStyleSheet(_fromUtf8("color: rgb(0, 85, 255);\n"
""))
        self.jobInfosGroupBox.setObjectName(_fromUtf8("jobInfosGroupBox"))
        self.horizontalLayout_11 = QtGui.QHBoxLayout(self.jobInfosGroupBox)
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.jobIdLabel_1 = QtGui.QLabel(self.jobInfosGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.jobIdLabel_1.sizePolicy().hasHeightForWidth())
        self.jobIdLabel_1.setSizePolicy(sizePolicy)
        self.jobIdLabel_1.setMinimumSize(QtCore.QSize(0, 0))
        self.jobIdLabel_1.setStyleSheet(_fromUtf8("color: rgb(0, 0, 0);"))
        self.jobIdLabel_1.setObjectName(_fromUtf8("jobIdLabel_1"))
        self.horizontalLayout.addWidget(self.jobIdLabel_1)
        self.jobIdLabel_2 = QtGui.QLabel(self.jobInfosGroupBox)
        self.jobIdLabel_2.setStyleSheet(_fromUtf8("color: rgb(0, 0, 0);"))
        self.jobIdLabel_2.setText(_fromUtf8(""))
        self.jobIdLabel_2.setObjectName(_fromUtf8("jobIdLabel_2"))
        self.horizontalLayout.addWidget(self.jobIdLabel_2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.technoLayerLabel_1 = QtGui.QLabel(self.jobInfosGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.technoLayerLabel_1.sizePolicy().hasHeightForWidth())
        self.technoLayerLabel_1.setSizePolicy(sizePolicy)
        self.technoLayerLabel_1.setMinimumSize(QtCore.QSize(0, 0))
        self.technoLayerLabel_1.setStyleSheet(_fromUtf8("color: rgb(0, 0, 0);"))
        self.technoLayerLabel_1.setObjectName(_fromUtf8("technoLayerLabel_1"))
        self.horizontalLayout_8.addWidget(self.technoLayerLabel_1)
        self.technoLayerLabel_2 = QtGui.QLabel(self.jobInfosGroupBox)
        self.technoLayerLabel_2.setStyleSheet(_fromUtf8("color: rgb(0, 0, 0);"))
        self.technoLayerLabel_2.setText(_fromUtf8(""))
        self.technoLayerLabel_2.setObjectName(_fromUtf8("technoLayerLabel_2"))
        self.horizontalLayout_8.addWidget(self.technoLayerLabel_2)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.dateLabel_1 = QtGui.QLabel(self.jobInfosGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dateLabel_1.sizePolicy().hasHeightForWidth())
        self.dateLabel_1.setSizePolicy(sizePolicy)
        self.dateLabel_1.setMinimumSize(QtCore.QSize(0, 0))
        self.dateLabel_1.setStyleSheet(_fromUtf8("color: rgb(0, 0, 0);"))
        self.dateLabel_1.setObjectName(_fromUtf8("dateLabel_1"))
        self.horizontalLayout_9.addWidget(self.dateLabel_1)
        self.dateLabel_2 = QtGui.QLabel(self.jobInfosGroupBox)
        self.dateLabel_2.setStyleSheet(_fromUtf8("color: rgb(0, 0, 0);"))
        self.dateLabel_2.setText(_fromUtf8(""))
        self.dateLabel_2.setObjectName(_fromUtf8("dateLabel_2"))
        self.horizontalLayout_9.addWidget(self.dateLabel_2)
        self.verticalLayout.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.gdsLabel_1 = QtGui.QLabel(self.jobInfosGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gdsLabel_1.sizePolicy().hasHeightForWidth())
        self.gdsLabel_1.setSizePolicy(sizePolicy)
        self.gdsLabel_1.setMinimumSize(QtCore.QSize(0, 0))
        self.gdsLabel_1.setStyleSheet(_fromUtf8("color: rgb(0, 0, 0);"))
        self.gdsLabel_1.setObjectName(_fromUtf8("gdsLabel_1"))
        self.horizontalLayout_10.addWidget(self.gdsLabel_1)
        self.gdsLabel_2 = QtGui.QLabel(self.jobInfosGroupBox)
        self.gdsLabel_2.setStyleSheet(_fromUtf8("color: rgb(0, 0, 0);"))
        self.gdsLabel_2.setText(_fromUtf8(""))
        self.gdsLabel_2.setObjectName(_fromUtf8("gdsLabel_2"))
        self.horizontalLayout_10.addWidget(self.gdsLabel_2)
        self.verticalLayout.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.brionVersionLabel_1 = QtGui.QLabel(self.jobInfosGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.brionVersionLabel_1.sizePolicy().hasHeightForWidth())
        self.brionVersionLabel_1.setSizePolicy(sizePolicy)
        self.brionVersionLabel_1.setMinimumSize(QtCore.QSize(0, 0))
        self.brionVersionLabel_1.setStyleSheet(_fromUtf8("color: rgb(0, 0, 0);"))
        self.brionVersionLabel_1.setObjectName(_fromUtf8("brionVersionLabel_1"))
        self.horizontalLayout_7.addWidget(self.brionVersionLabel_1)
        self.brionVersionLabel_2 = QtGui.QLabel(self.jobInfosGroupBox)
        self.brionVersionLabel_2.setStyleSheet(_fromUtf8("color: rgb(0, 0, 0);"))
        self.brionVersionLabel_2.setText(_fromUtf8(""))
        self.brionVersionLabel_2.setObjectName(_fromUtf8("brionVersionLabel_2"))
        self.horizontalLayout_7.addWidget(self.brionVersionLabel_2)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_11.addLayout(self.verticalLayout)
        self.horizontalLayout_2.addWidget(self.jobInfosGroupBox)
        self.ratInfosGroupBox = QtGui.QGroupBox(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MS Shell Dlg 2"))
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.ratInfosGroupBox.setFont(font)
        self.ratInfosGroupBox.setStyleSheet(_fromUtf8("font: 75 8pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 85, 255);"))
        self.ratInfosGroupBox.setObjectName(_fromUtf8("ratInfosGroupBox"))
        self.horizontalLayout_12 = QtGui.QHBoxLayout(self.ratInfosGroupBox)
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.masksetLabel_1 = QtGui.QLabel(self.ratInfosGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.masksetLabel_1.sizePolicy().hasHeightForWidth())
        self.masksetLabel_1.setSizePolicy(sizePolicy)
        self.masksetLabel_1.setMinimumSize(QtCore.QSize(0, 0))
        self.masksetLabel_1.setStyleSheet(_fromUtf8("color: rgb(0, 0, 0);"))
        self.masksetLabel_1.setObjectName(_fromUtf8("masksetLabel_1"))
        self.horizontalLayout_13.addWidget(self.masksetLabel_1)
        self.masksetLabel_2 = QtGui.QLabel(self.ratInfosGroupBox)
        self.masksetLabel_2.setStyleSheet(_fromUtf8("color: rgb(0, 0, 0);"))
        self.masksetLabel_2.setText(_fromUtf8(""))
        self.masksetLabel_2.setObjectName(_fromUtf8("masksetLabel_2"))
        self.horizontalLayout_13.addWidget(self.masksetLabel_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.blockLabel_1 = QtGui.QLabel(self.ratInfosGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.blockLabel_1.sizePolicy().hasHeightForWidth())
        self.blockLabel_1.setSizePolicy(sizePolicy)
        self.blockLabel_1.setMinimumSize(QtCore.QSize(0, 0))
        self.blockLabel_1.setStyleSheet(_fromUtf8("color: rgb(0, 0, 0);"))
        self.blockLabel_1.setObjectName(_fromUtf8("blockLabel_1"))
        self.horizontalLayout_14.addWidget(self.blockLabel_1)
        self.blockLabel_2 = QtGui.QLabel(self.ratInfosGroupBox)
        self.blockLabel_2.setStyleSheet(_fromUtf8("color: rgb(0, 0, 0);\n"
"color: rgb(0, 0, 0);"))
        self.blockLabel_2.setText(_fromUtf8(""))
        self.blockLabel_2.setObjectName(_fromUtf8("blockLabel_2"))
        self.horizontalLayout_14.addWidget(self.blockLabel_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        self.productLabel_1 = QtGui.QLabel(self.ratInfosGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.productLabel_1.sizePolicy().hasHeightForWidth())
        self.productLabel_1.setSizePolicy(sizePolicy)
        self.productLabel_1.setMinimumSize(QtCore.QSize(0, 0))
        self.productLabel_1.setStyleSheet(_fromUtf8("color: rgb(0, 0, 0);"))
        self.productLabel_1.setObjectName(_fromUtf8("productLabel_1"))
        self.horizontalLayout_15.addWidget(self.productLabel_1)
        self.productLabel_2 = QtGui.QLabel(self.ratInfosGroupBox)
        self.productLabel_2.setStyleSheet(_fromUtf8("color: rgb(0, 0, 0);"))
        self.productLabel_2.setText(_fromUtf8(""))
        self.productLabel_2.setObjectName(_fromUtf8("productLabel_2"))
        self.horizontalLayout_15.addWidget(self.productLabel_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_16 = QtGui.QHBoxLayout()
        self.horizontalLayout_16.setObjectName(_fromUtf8("horizontalLayout_16"))
        self.mridLabel_1 = QtGui.QLabel(self.ratInfosGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mridLabel_1.sizePolicy().hasHeightForWidth())
        self.mridLabel_1.setSizePolicy(sizePolicy)
        self.mridLabel_1.setMinimumSize(QtCore.QSize(0, 0))
        self.mridLabel_1.setStyleSheet(_fromUtf8("color: rgb(0, 0, 0);"))
        self.mridLabel_1.setObjectName(_fromUtf8("mridLabel_1"))
        self.horizontalLayout_16.addWidget(self.mridLabel_1)
        self.mridLabel_2 = QtGui.QLabel(self.ratInfosGroupBox)
        self.mridLabel_2.setStyleSheet(_fromUtf8("color: rgb(0, 0, 0);"))
        self.mridLabel_2.setText(_fromUtf8(""))
        self.mridLabel_2.setObjectName(_fromUtf8("mridLabel_2"))
        self.horizontalLayout_16.addWidget(self.mridLabel_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_17 = QtGui.QHBoxLayout()
        self.horizontalLayout_17.setObjectName(_fromUtf8("horizontalLayout_17"))
        self.jobTypeLabel_1 = QtGui.QLabel(self.ratInfosGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.jobTypeLabel_1.sizePolicy().hasHeightForWidth())
        self.jobTypeLabel_1.setSizePolicy(sizePolicy)
        self.jobTypeLabel_1.setMinimumSize(QtCore.QSize(0, 0))
        self.jobTypeLabel_1.setStyleSheet(_fromUtf8("color: rgb(0, 0, 0);"))
        self.jobTypeLabel_1.setObjectName(_fromUtf8("jobTypeLabel_1"))
        self.horizontalLayout_17.addWidget(self.jobTypeLabel_1)
        self.jobTypeLabel_2 = QtGui.QLabel(self.ratInfosGroupBox)
        self.jobTypeLabel_2.setStyleSheet(_fromUtf8("color: rgb(0, 0, 0);"))
        self.jobTypeLabel_2.setText(_fromUtf8(""))
        self.jobTypeLabel_2.setObjectName(_fromUtf8("jobTypeLabel_2"))
        self.horizontalLayout_17.addWidget(self.jobTypeLabel_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_12.addLayout(self.verticalLayout_2)
        self.horizontalLayout_2.addWidget(self.ratInfosGroupBox)
        self.verticalLayout_9.addLayout(self.horizontalLayout_2)
        self.opcInfosGroupBox = QtGui.QGroupBox(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MS Shell Dlg 2"))
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.opcInfosGroupBox.setFont(font)
        self.opcInfosGroupBox.setStyleSheet(_fromUtf8("font: 75 8pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 85, 255);"))
        self.opcInfosGroupBox.setObjectName(_fromUtf8("opcInfosGroupBox"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.opcInfosGroupBox)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.xopRouteLabel_1 = QtGui.QLabel(self.opcInfosGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.xopRouteLabel_1.sizePolicy().hasHeightForWidth())
        self.xopRouteLabel_1.setSizePolicy(sizePolicy)
        self.xopRouteLabel_1.setMinimumSize(QtCore.QSize(0, 0))
        self.xopRouteLabel_1.setStyleSheet(_fromUtf8("color: rgb(0, 0, 0);"))
        self.xopRouteLabel_1.setObjectName(_fromUtf8("xopRouteLabel_1"))
        self.horizontalLayout_3.addWidget(self.xopRouteLabel_1)
        self.xopRouteLabel_2 = QtGui.QLabel(self.opcInfosGroupBox)
        self.xopRouteLabel_2.setStyleSheet(_fromUtf8("color: rgb(0, 0, 0);"))
        self.xopRouteLabel_2.setText(_fromUtf8(""))
        self.xopRouteLabel_2.setObjectName(_fromUtf8("xopRouteLabel_2"))
        self.horizontalLayout_3.addWidget(self.xopRouteLabel_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_19 = QtGui.QHBoxLayout()
        self.horizontalLayout_19.setObjectName(_fromUtf8("horizontalLayout_19"))
        self.opcPackageLabel_1 = QtGui.QLabel(self.opcInfosGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.opcPackageLabel_1.sizePolicy().hasHeightForWidth())
        self.opcPackageLabel_1.setSizePolicy(sizePolicy)
        self.opcPackageLabel_1.setMinimumSize(QtCore.QSize(0, 0))
        self.opcPackageLabel_1.setStyleSheet(_fromUtf8("color: rgb(0, 0, 0);"))
        self.opcPackageLabel_1.setObjectName(_fromUtf8("opcPackageLabel_1"))
        self.horizontalLayout_19.addWidget(self.opcPackageLabel_1)
        self.opcPackageLabel_2 = QtGui.QLabel(self.opcInfosGroupBox)
        self.opcPackageLabel_2.setStyleSheet(_fromUtf8("color: rgb(0, 0, 0);"))
        self.opcPackageLabel_2.setText(_fromUtf8(""))
        self.opcPackageLabel_2.setObjectName(_fromUtf8("opcPackageLabel_2"))
        self.horizontalLayout_19.addWidget(self.opcPackageLabel_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_19)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        spacerItem = QtGui.QSpacerItem(10, 10, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout_4.addItem(spacerItem)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        spacerItem1 = QtGui.QSpacerItem(202, 50, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem1)
        self.viewHistoButton = QtGui.QPushButton(self.opcInfosGroupBox)
        self.viewHistoButton.setStyleSheet(_fromUtf8("color: rgb(0, 0, 0);"))
        self.viewHistoButton.setObjectName(_fromUtf8("viewHistoButton"))
        self.horizontalLayout_6.addWidget(self.viewHistoButton)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem2)
        self.label_4 = QtGui.QLabel(self.opcInfosGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setMinimumSize(QtCore.QSize(0, 0))
        self.label_4.setText(_fromUtf8(""))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_6.addWidget(self.label_4)
        self.verticalLayout_4.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_4.addLayout(self.verticalLayout_4)
        self.verticalLayout_9.addWidget(self.opcInfosGroupBox)
        self.verticalLayout_10.addLayout(self.verticalLayout_9)
        self.verticalLayout_8 = QtGui.QVBoxLayout()
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.resultsGroupBox = QtGui.QGroupBox(self.centralwidget)
        self.resultsGroupBox.setStyleSheet(_fromUtf8("color: rgb(0, 85, 255);"))
        self.resultsGroupBox.setObjectName(_fromUtf8("resultsGroupBox"))
        self.horizontalLayout_31 = QtGui.QHBoxLayout(self.resultsGroupBox)
        self.horizontalLayout_31.setObjectName(_fromUtf8("horizontalLayout_31"))
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.horizontalLayout_29 = QtGui.QHBoxLayout()
        self.horizontalLayout_29.setObjectName(_fromUtf8("horizontalLayout_29"))
        self.retDbDefectsInfosGroupBox = QtGui.QGroupBox(self.resultsGroupBox)
        self.retDbDefectsInfosGroupBox.setObjectName(_fromUtf8("retDbDefectsInfosGroupBox"))
        self.horizontalLayout_24 = QtGui.QHBoxLayout(self.retDbDefectsInfosGroupBox)
        self.horizontalLayout_24.setObjectName(_fromUtf8("horizontalLayout_24"))
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.horizontalLayout_18 = QtGui.QHBoxLayout()
        self.horizontalLayout_18.setObjectName(_fromUtf8("horizontalLayout_18"))
        self.defectsLabel_1 = QtGui.QLabel(self.retDbDefectsInfosGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.defectsLabel_1.sizePolicy().hasHeightForWidth())
        self.defectsLabel_1.setSizePolicy(sizePolicy)
        self.defectsLabel_1.setMinimumSize(QtCore.QSize(0, 0))
        self.defectsLabel_1.setStyleSheet(_fromUtf8("color: rgb(0, 0, 0);"))
        self.defectsLabel_1.setObjectName(_fromUtf8("defectsLabel_1"))
        self.horizontalLayout_18.addWidget(self.defectsLabel_1)
        self.defectsLabel_2 = QtGui.QLabel(self.retDbDefectsInfosGroupBox)
        self.defectsLabel_2.setStyleSheet(_fromUtf8("color: rgb(0, 0, 0);"))
        self.defectsLabel_2.setText(_fromUtf8(""))
        self.defectsLabel_2.setObjectName(_fromUtf8("defectsLabel_2"))
        self.horizontalLayout_18.addWidget(self.defectsLabel_2)
        self.verticalLayout_5.addLayout(self.horizontalLayout_18)
        self.horizontalLayout_20 = QtGui.QHBoxLayout()
        self.horizontalLayout_20.setObjectName(_fromUtf8("horizontalLayout_20"))
        self.allreadyInRetDbLabel_1 = QtGui.QLabel(self.retDbDefectsInfosGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.allreadyInRetDbLabel_1.sizePolicy().hasHeightForWidth())
        self.allreadyInRetDbLabel_1.setSizePolicy(sizePolicy)
        self.allreadyInRetDbLabel_1.setMinimumSize(QtCore.QSize(0, 0))
        self.allreadyInRetDbLabel_1.setStyleSheet(_fromUtf8("color: rgb(0, 0, 0);"))
        self.allreadyInRetDbLabel_1.setObjectName(_fromUtf8("allreadyInRetDbLabel_1"))
        self.horizontalLayout_20.addWidget(self.allreadyInRetDbLabel_1)
        self.allreadyInRetDbLabel_2 = QtGui.QLabel(self.retDbDefectsInfosGroupBox)
        self.allreadyInRetDbLabel_2.setStyleSheet(_fromUtf8("color: rgb(0, 0, 0);"))
        self.allreadyInRetDbLabel_2.setText(_fromUtf8(""))
        self.allreadyInRetDbLabel_2.setObjectName(_fromUtf8("allreadyInRetDbLabel_2"))
        self.horizontalLayout_20.addWidget(self.allreadyInRetDbLabel_2)
        self.verticalLayout_5.addLayout(self.horizontalLayout_20)
        self.horizontalLayout_21 = QtGui.QHBoxLayout()
        self.horizontalLayout_21.setObjectName(_fromUtf8("horizontalLayout_21"))
        self.addInRetDbLabel_1 = QtGui.QLabel(self.retDbDefectsInfosGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.addInRetDbLabel_1.sizePolicy().hasHeightForWidth())
        self.addInRetDbLabel_1.setSizePolicy(sizePolicy)
        self.addInRetDbLabel_1.setMinimumSize(QtCore.QSize(0, 0))
        self.addInRetDbLabel_1.setStyleSheet(_fromUtf8("color: rgb(0, 0, 0);"))
        self.addInRetDbLabel_1.setObjectName(_fromUtf8("addInRetDbLabel_1"))
        self.horizontalLayout_21.addWidget(self.addInRetDbLabel_1)
        self.addInRetDbLabel_2 = QtGui.QLabel(self.retDbDefectsInfosGroupBox)
        self.addInRetDbLabel_2.setStyleSheet(_fromUtf8("color: rgb(0, 0, 0);"))
        self.addInRetDbLabel_2.setObjectName(_fromUtf8("addInRetDbLabel_2"))
        self.horizontalLayout_21.addWidget(self.addInRetDbLabel_2)
        self.verticalLayout_5.addLayout(self.horizontalLayout_21)
        self.horizontalLayout_24.addLayout(self.verticalLayout_5)
        self.horizontalLayout_29.addWidget(self.retDbDefectsInfosGroupBox)
        self.retValidCriticityGroupBox = QtGui.QGroupBox(self.resultsGroupBox)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MS Shell Dlg 2"))
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.retValidCriticityGroupBox.setFont(font)
        self.retValidCriticityGroupBox.setStyleSheet(_fromUtf8("font: 75 8pt \"MS Shell Dlg 2\";"))
        self.retValidCriticityGroupBox.setObjectName(_fromUtf8("retValidCriticityGroupBox"))
        self.horizontalLayout_22 = QtGui.QHBoxLayout(self.retValidCriticityGroupBox)
        self.horizontalLayout_22.setObjectName(_fromUtf8("horizontalLayout_22"))
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.horizontalLayout_23 = QtGui.QHBoxLayout()
        self.horizontalLayout_23.setObjectName(_fromUtf8("horizontalLayout_23"))
        self.unknownLabel_1 = QtGui.QLabel(self.retValidCriticityGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.unknownLabel_1.sizePolicy().hasHeightForWidth())
        self.unknownLabel_1.setSizePolicy(sizePolicy)
        self.unknownLabel_1.setMinimumSize(QtCore.QSize(0, 0))
        self.unknownLabel_1.setStyleSheet(_fromUtf8("color: rgb(0, 0, 0);"))
        self.unknownLabel_1.setObjectName(_fromUtf8("unknownLabel_1"))
        self.horizontalLayout_23.addWidget(self.unknownLabel_1)
        self.unknownLabel_2 = QtGui.QLabel(self.retValidCriticityGroupBox)
        self.unknownLabel_2.setStyleSheet(_fromUtf8("color: rgb(0, 0, 0);"))
        self.unknownLabel_2.setText(_fromUtf8(""))
        self.unknownLabel_2.setObjectName(_fromUtf8("unknownLabel_2"))
        self.horizontalLayout_23.addWidget(self.unknownLabel_2)
        self.verticalLayout_6.addLayout(self.horizontalLayout_23)
        self.horizontalLayout_28 = QtGui.QHBoxLayout()
        self.horizontalLayout_28.setObjectName(_fromUtf8("horizontalLayout_28"))
        self.acceptLabel_1 = QtGui.QLabel(self.retValidCriticityGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.acceptLabel_1.sizePolicy().hasHeightForWidth())
        self.acceptLabel_1.setSizePolicy(sizePolicy)
        self.acceptLabel_1.setMinimumSize(QtCore.QSize(0, 0))
        self.acceptLabel_1.setStyleSheet(_fromUtf8("color: rgb(0, 0, 0);"))
        self.acceptLabel_1.setObjectName(_fromUtf8("acceptLabel_1"))
        self.horizontalLayout_28.addWidget(self.acceptLabel_1)
        self.acceptLabel_2 = QtGui.QLabel(self.retValidCriticityGroupBox)
        self.acceptLabel_2.setStyleSheet(_fromUtf8("color: rgb(0, 0, 0);"))
        self.acceptLabel_2.setText(_fromUtf8(""))
        self.acceptLabel_2.setObjectName(_fromUtf8("acceptLabel_2"))
        self.horizontalLayout_28.addWidget(self.acceptLabel_2)
        self.verticalLayout_6.addLayout(self.horizontalLayout_28)
        self.horizontalLayout_25 = QtGui.QHBoxLayout()
        self.horizontalLayout_25.setObjectName(_fromUtf8("horizontalLayout_25"))
        self.holdLabel_1 = QtGui.QLabel(self.retValidCriticityGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.holdLabel_1.sizePolicy().hasHeightForWidth())
        self.holdLabel_1.setSizePolicy(sizePolicy)
        self.holdLabel_1.setMinimumSize(QtCore.QSize(0, 0))
        self.holdLabel_1.setStyleSheet(_fromUtf8("color: rgb(0, 0, 0);"))
        self.holdLabel_1.setObjectName(_fromUtf8("holdLabel_1"))
        self.horizontalLayout_25.addWidget(self.holdLabel_1)
        self.holdLabel_2 = QtGui.QLabel(self.retValidCriticityGroupBox)
        self.holdLabel_2.setStyleSheet(_fromUtf8("color: rgb(0, 0, 0);"))
        self.holdLabel_2.setText(_fromUtf8(""))
        self.holdLabel_2.setObjectName(_fromUtf8("holdLabel_2"))
        self.horizontalLayout_25.addWidget(self.holdLabel_2)
        self.verticalLayout_6.addLayout(self.horizontalLayout_25)
        self.horizontalLayout_26 = QtGui.QHBoxLayout()
        self.horizontalLayout_26.setObjectName(_fromUtf8("horizontalLayout_26"))
        self.rejectLabel_1 = QtGui.QLabel(self.retValidCriticityGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rejectLabel_1.sizePolicy().hasHeightForWidth())
        self.rejectLabel_1.setSizePolicy(sizePolicy)
        self.rejectLabel_1.setMinimumSize(QtCore.QSize(0, 0))
        self.rejectLabel_1.setStyleSheet(_fromUtf8("color: rgb(0, 0, 0);"))
        self.rejectLabel_1.setObjectName(_fromUtf8("rejectLabel_1"))
        self.horizontalLayout_26.addWidget(self.rejectLabel_1)
        self.rejectLabel_2 = QtGui.QLabel(self.retValidCriticityGroupBox)
        self.rejectLabel_2.setStyleSheet(_fromUtf8("color: rgb(0, 0, 0);"))
        self.rejectLabel_2.setText(_fromUtf8(""))
        self.rejectLabel_2.setObjectName(_fromUtf8("rejectLabel_2"))
        self.horizontalLayout_26.addWidget(self.rejectLabel_2)
        self.verticalLayout_6.addLayout(self.horizontalLayout_26)
        self.horizontalLayout_27 = QtGui.QHBoxLayout()
        self.horizontalLayout_27.setObjectName(_fromUtf8("horizontalLayout_27"))
        self.needImprovementLabel_1 = QtGui.QLabel(self.retValidCriticityGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.needImprovementLabel_1.sizePolicy().hasHeightForWidth())
        self.needImprovementLabel_1.setSizePolicy(sizePolicy)
        self.needImprovementLabel_1.setMinimumSize(QtCore.QSize(0, 0))
        self.needImprovementLabel_1.setStyleSheet(_fromUtf8("color: rgb(0, 0, 0);"))
        self.needImprovementLabel_1.setObjectName(_fromUtf8("needImprovementLabel_1"))
        self.horizontalLayout_27.addWidget(self.needImprovementLabel_1)
        self.needImprovementLabel_2 = QtGui.QLabel(self.retValidCriticityGroupBox)
        self.needImprovementLabel_2.setStyleSheet(_fromUtf8("color: rgb(0, 0, 0);"))
        self.needImprovementLabel_2.setText(_fromUtf8(""))
        self.needImprovementLabel_2.setObjectName(_fromUtf8("needImprovementLabel_2"))
        self.horizontalLayout_27.addWidget(self.needImprovementLabel_2)
        self.verticalLayout_6.addLayout(self.horizontalLayout_27)
        self.horizontalLayout_22.addLayout(self.verticalLayout_6)
        self.horizontalLayout_29.addWidget(self.retValidCriticityGroupBox)
        spacerItem3 = QtGui.QSpacerItem(80, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_29.addItem(spacerItem3)
        self.jobDefectClassificationButton = QtGui.QPushButton(self.resultsGroupBox)
        self.jobDefectClassificationButton.setStyleSheet(_fromUtf8("color: rgb(0, 0, 0);"))
        self.jobDefectClassificationButton.setObjectName(_fromUtf8("jobDefectClassificationButton"))
        self.horizontalLayout_29.addWidget(self.jobDefectClassificationButton)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_29.addItem(spacerItem4)
        self.verticalLayout_7.addLayout(self.horizontalLayout_29)
        self.table_1 = QtGui.QTableWidget(self.resultsGroupBox)
        self.table_1.setStyleSheet(_fromUtf8("color: rgb(47, 79,79)"))
        self.table_1.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.table_1.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.table_1.setObjectName(_fromUtf8("table_1"))
        self.table_1.setColumnCount(8)
        self.table_1.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.table_1.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.table_1.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.table_1.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.table_1.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.table_1.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.table_1.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.table_1.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.table_1.setHorizontalHeaderItem(7, item)
        self.verticalLayout_7.addWidget(self.table_1)
        self.horizontalLayout_31.addLayout(self.verticalLayout_7)
        self.verticalLayout_8.addWidget(self.resultsGroupBox)
        self.kpiGroupBox = QtGui.QGroupBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.kpiGroupBox.sizePolicy().hasHeightForWidth())
        self.kpiGroupBox.setSizePolicy(sizePolicy)
        self.kpiGroupBox.setMinimumSize(QtCore.QSize(741, 131))
        self.kpiGroupBox.setStyleSheet(_fromUtf8("color: rgb(0, 85, 255);"))
        self.kpiGroupBox.setObjectName(_fromUtf8("kpiGroupBox"))
        self.horizontalLayout_30 = QtGui.QHBoxLayout(self.kpiGroupBox)
        self.horizontalLayout_30.setObjectName(_fromUtf8("horizontalLayout_30"))
        self.table_2 = QtGui.QTableWidget(self.kpiGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.table_2.sizePolicy().hasHeightForWidth())
        self.table_2.setSizePolicy(sizePolicy)
        self.table_2.setStyleSheet(_fromUtf8("color: rgb(47,79,79);"))
        self.table_2.setObjectName(_fromUtf8("table_2"))
        self.table_2.setColumnCount(8)
        self.table_2.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.table_2.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.table_2.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.table_2.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.table_2.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.table_2.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.table_2.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.table_2.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.table_2.setHorizontalHeaderItem(7, item)
        self.horizontalLayout_30.addWidget(self.table_2)
        self.verticalLayout_8.addWidget(self.kpiGroupBox)
        self.verticalLayout_10.addLayout(self.verticalLayout_8)
        self.pushButton = QtGui.QPushButton(self.centralwidget)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.verticalLayout_10.addWidget(self.pushButton)
        mainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(mainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 862, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        mainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(mainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        mainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        mainWindow.setWindowTitle(_translate("mainWindow", "job identity Card", None))
        self.jobInfosGroupBox.setTitle(_translate("mainWindow", "job Infos", None))
        self.jobIdLabel_1.setText(_translate("mainWindow", "job ID.........", None))
        self.technoLayerLabel_1.setText(_translate("mainWindow", "Techno Layer  ", None))
        self.dateLabel_1.setText(_translate("mainWindow", "Date............", None))
        self.gdsLabel_1.setText(_translate("mainWindow", "GDS.............", None))
        self.brionVersionLabel_1.setText(_translate("mainWindow", "Brion version..", None))
        self.ratInfosGroupBox.setTitle(_translate("mainWindow", "Rat Infos", None))
        self.masksetLabel_1.setText(_translate("mainWindow", "Maskset.......", None))
        self.blockLabel_1.setText(_translate("mainWindow", "Block...........", None))
        self.productLabel_1.setText(_translate("mainWindow", "Product....... ", None))
        self.mridLabel_1.setText(_translate("mainWindow", "MRID..........", None))
        self.jobTypeLabel_1.setText(_translate("mainWindow", "job Type......", None))
        self.opcInfosGroupBox.setTitle(_translate("mainWindow", "Opc Infos", None))
        self.xopRouteLabel_1.setText(_translate("mainWindow", "XOP route.....", None))
        self.opcPackageLabel_1.setText(_translate("mainWindow", "OPC Package..", None))
        self.viewHistoButton.setText(_translate("mainWindow", "View Histo", None))
        self.resultsGroupBox.setTitle(_translate("mainWindow", "Results", None))
        self.retDbDefectsInfosGroupBox.setTitle(_translate("mainWindow", "RetDB Defects Infos", None))
        self.defectsLabel_1.setText(_translate("mainWindow", "Defects:               ", None))
        self.allreadyInRetDbLabel_1.setText(_translate("mainWindow", "Allready in RetDB: ", None))
        self.addInRetDbLabel_1.setText(_translate("mainWindow", "Add in Retdb:        ", None))
        self.addInRetDbLabel_2.setText(_translate("mainWindow", ".", None))
        self.retValidCriticityGroupBox.setTitle(_translate("mainWindow", "Ret Valid Criticity", None))
        self.unknownLabel_1.setText(_translate("mainWindow", "UnKnown:                ", None))
        self.acceptLabel_1.setText(_translate("mainWindow", "Accept:                     ", None))
        self.holdLabel_1.setText(_translate("mainWindow", "Hold                          ", None))
        self.rejectLabel_1.setText(_translate("mainWindow", "Reject:                     ", None))
        self.needImprovementLabel_1.setText(_translate("mainWindow", "Need Improvement: ", None))
        self.jobDefectClassificationButton.setText(_translate("mainWindow", "job Defects\n"
" Classification", None))
        item = self.table_1.horizontalHeaderItem(0)
        item.setText(_translate("mainWindow", "Detector", None))
        item = self.table_1.horizontalHeaderItem(1)
        item.setText(_translate("mainWindow", "Subjob", None))
        item = self.table_1.horizontalHeaderItem(2)
        item.setText(_translate("mainWindow", "Dose", None))
        item = self.table_1.horizontalHeaderItem(3)
        item.setText(_translate("mainWindow", "Focus", None))
        item = self.table_1.horizontalHeaderItem(4)
        item.setText(_translate("mainWindow", "Bias", None))
        item = self.table_1.horizontalHeaderItem(5)
        item.setText(_translate("mainWindow", "Worst", None))
        item = self.table_1.horizontalHeaderItem(6)
        item.setText(_translate("mainWindow", "Defects", None))
        item = self.table_1.horizontalHeaderItem(7)
        item.setText(_translate("mainWindow", "Category(Name)", None))
        self.kpiGroupBox.setTitle(_translate("mainWindow", "KPI", None))
        item = self.table_2.horizontalHeaderItem(0)
        item.setText(_translate("mainWindow", "Detector", None))
        item = self.table_2.horizontalHeaderItem(1)
        item.setText(_translate("mainWindow", "Dose", None))
        item = self.table_2.horizontalHeaderItem(2)
        item.setText(_translate("mainWindow", "Focus", None))
        item = self.table_2.horizontalHeaderItem(3)
        item.setText(_translate("mainWindow", "Bias", None))
        item = self.table_2.horizontalHeaderItem(4)
        item.setText(_translate("mainWindow", "Worst", None))
        item = self.table_2.horizontalHeaderItem(5)
        item.setText(_translate("mainWindow", "KPI", None))
        item = self.table_2.horizontalHeaderItem(6)
        item.setText(_translate("mainWindow", "ALARM?", None))
        item = self.table_2.horizontalHeaderItem(7)
        item.setText(_translate("mainWindow", "Categorized", None))
        self.pushButton.setText(_translate("mainWindow", "Exit", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    mainWindow = QtGui.QMainWindow()
    ui = Ui_mainWindow()
    ui.setupUi(mainWindow)
    mainWindow.show()
    sys.exit(app.exec_())
